[package]
name = "rusty-game"
version = "0.1.0"
authors = ["corrina <csivak345@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = {version="0.33", features=["bundled"]}